export enum ActivitySportType {
    AlpineSki="Alpine Ski",
    BackcountrySki="Backcountry Ski",
    Badminton="Badminton",
    Canoeing="Canoeing",
    Crossfit="Crossfit",
    EBikeRide="EBike Ride",
    Elliptical="Elliptical",
    EMountainBikeRide="EMountain Bike Ride",
    Golf="Golf",
    GravelRide="Gravel Ride",
    Handcycle="Handcycle",
    HighIntensityIntervalTraining="High Intensity Interval Training",
    Hike="Hike",
    IceSkate="Ice Skate",
    InlineSkate="Inline Skate",
    Kayaking="Kayaking",
    Kitesurf="Kitesurf",
    MountainBikeRide="Mountain Bike Ride",
    NordicSki="Nordic Ski",
    Pickleball="Pickleball",
    Pilates="Pilates",
    Racquetball="Racquetball",
    Ride="Ride",
    RockClimbing="Rock Climbing",
    RollerSki="Roller Ski",
    Rowing="Rowing",
    Run="Run",
    Sail="Sail",
    Skateboard="Skateboard",
    Snowboard="Snowboard",
    Snowshoe="Snowshoe",
    Soccer="Soccer",
    Squash="Squash",
    StairStepper="Stair Stepper",
    StandUpPaddling="Stand Up Paddling",
    Surfing="Surfing",
    Swim="Swim",
    TableTennis="Table Tennis",
    Tennis="Tennis",
    TrailRun="Trail Run",
    Velomobile="Velomobile",
    VirtualRide="Virtual Ride",
    VirtualRow="Virtual Row",
    VirtualRun="Virtual Run",
    Walk="Walk",
    WeightTraining="Weight Training",
    Wheelchair="Wheelchair",
    Windsurf="Windsurf",
    Workout="Workout",
    Yoga="Yoga",
}

export class Athlete {
    constructor (
        public id?: string,
        public username?: string,
        public resource_state?: string,
        public firstname?: string,
        public lastname?: string,
        public bio?: string,
        public city?: string,
        public state?: string,
        public country?: string,
        public sex?: string,
        public premium?: string,
        public summit?: string,
        public created_at?: string,
        public updated_at?: string,
        public badge_type_id?: string,
        public weight?: string,
        public profile_medium?: string,
        public profile?: string,
        public friend?: string,
        public follower?: string,
    ) {}
}

export class ClubActivity {
    constructor (
        public athlete?: Athlete,
        public name?: string,
        public distance?: number,
        public moving_time?: number,
        public elapsed_time?: number,
        public total_elevation_gain?: number,
        public sport_type?: ActivitySportType,
        public workout_type?: number,
    ) {}
}

export class AthleteActivity {
    constructor (
        public id: number,
        public external_id: number,
        public resource_state: number,
        public athlete: Athlete,
        public name: string,
        public distance: number,
        public moving_time: number,
        public elapsed_time: number,
        public total_elevation_gain: number,
        public sport_type: ActivitySportType,
        public workout_type: number,
        public upload_id: number,
        public start_date: string,
        public start_date_local: string,
        public timezone: string,
        public start_latlng: string, // LatLng
        public end_latlng: string, // LatLng
        public location_city: string,
        public location_state: string,
        public location_country: string,
        public achievement_count: number,
        public kudos_count: number,
        public comment_count: number,
        public athlete_count: number,
        public photo_count: number,
        public map : Object, // PolylineMap
        public trainer: boolean,
        public commute: boolean,
        public manual: boolean,
        public isPrivate: boolean,
        public flagged: boolean,
        public gear_id: string,
        public average_speed: number,
        public max_speed: number,
        public average_cadence: number,
        public average_watts: number,
        public weighted_average_watts: number,
        public kilojoules: string,
        public device_watts: boolean,
        public has_heartrate: boolean,
        public average_heartrate: number,
        public max_heartrate: number,
        public max_watts: number,
        public pr_count: number,
        public total_photo_count: number,
        public has_kudoed: boolean,
    ) {}
}