export enum ActivitySportType {
    AlpineSki="AlpineSki",
    BackcountrySki="BackcountrySki",
    Badminton="Badminton",
    Canoeing="Canoeing",
    Crossfit="Crossfit",
    EBikeRide="EBikeRide",
    Elliptical="Elliptical",
    EMountainBikeRide="EMountainBikeRide",
    Golf="Golf",
    GravelRide="GravelRide",
    Handcycle="Handcycle",
    HighIntensityIntervalTraining="HighIntensityIntervalTraining",
    Hike="Hike",
    IceSkate="IceSkate",
    InlineSkate="InlineSkate",
    Kayaking="Kayaking",
    Kitesurf="Kitesurf",
    MountainBikeRide="MountainBikeRide",
    NordicSki="NordicSki",
    Pickleball="Pickleball",
    Pilates="Pilates",
    Racquetball="Racquetball",
    Ride="Ride",
    RockClimbing="RockClimbing",
    RollerSki="RollerSki",
    Rowing="Rowing",
    Run="Run",
    Sail="Sail",
    Skateboard="Skateboard",
    Snowboard="Snowboard",
    Snowshoe="Snowshoe",
    Soccer="Soccer",
    Squash="Squash",
    StairStepper="StairStepper",
    StandUpPaddling="StandUpPaddling",
    Surfing="Surfing",
    Swim="Swim",
    TableTennis="TableTennis",
    Tennis="Tennis",
    TrailRun="TrailRun",
    Velomobile="Velomobile",
    VirtualRide="VirtualRide",
    VirtualRow="VirtualRow",
    VirtualRun="VirtualRun",
    Walk="Walk",
    WeightTraining="WeightTraining",
    Wheelchair="Wheelchair",
    Windsurf="Windsurf",
    Workout="Workout",
    Yoga="Yoga",
}

export class Athlete {
    constructor (
        public id?: string,
        public username?: string,
        public resource_state?: string,
        public firstname?: string,
        public lastname?: string,
        public bio?: string,
        public city?: string,
        public state?: string,
        public country?: string,
        public sex?: string,
        public premium?: string,
        public summit?: string,
        public created_at?: string,
        public updated_at?: string,
        public badge_type_id?: string,
        public weight?: string,
        public profile_medium?: string,
        public profile?: string,
        public friend?: string,
        public follower?: string,
    ) {}
}

export class ClubActivity {
    constructor (
        public athlete?: Athlete,
        public name?: string,
        public distance?: number,
        public moving_time?: number,
        public elapsed_time?: number,
        public total_elevation_gain?: number,
        public sport_type?: ActivitySportType,
        public workout_type?: number,
    ) {}
}