export enum ActivitySportType {
    AlpineSki="Alpine Ski",
    BackcountrySki="Backcountry Ski",
    Badminton="Badminton",
    Canoeing="Canoeing",
    Crossfit="Crossfit",
    EBikeRide="EBike Ride",
    Elliptical="Elliptical",
    EMountainBikeRide="EMountain Bike Ride",
    Golf="Golf",
    GravelRide="Gravel Ride",
    Handcycle="Handcycle",
    HighIntensityIntervalTraining="High Intensity Interval Training",
    Hike="Hike",
    IceSkate="Ice Skate",
    InlineSkate="Inline Skate",
    Kayaking="Kayaking",
    Kitesurf="Kitesurf",
    MountainBikeRide="Mountain Bike Ride",
    NordicSki="Nordic Ski",
    Pickleball="Pickleball",
    Pilates="Pilates",
    Racquetball="Racquetball",
    Ride="Ride",
    RockClimbing="Rock Climbing",
    RollerSki="Roller Ski",
    Rowing="Rowing",
    Run="Run",
    Sail="Sail",
    Skateboard="Skateboard",
    Snowboard="Snowboard",
    Snowshoe="Snowshoe",
    Soccer="Soccer",
    Squash="Squash",
    StairStepper="Stair Stepper",
    StandUpPaddling="Stand Up Paddling",
    Surfing="Surfing",
    Swim="Swim",
    TableTennis="Table Tennis",
    Tennis="Tennis",
    TrailRun="Trail Run",
    Velomobile="Velomobile",
    VirtualRide="Virtual Ride",
    VirtualRow="Virtual Row",
    VirtualRun="Virtual Run",
    Walk="Walk",
    WeightTraining="Weight Training",
    Wheelchair="Wheelchair",
    Windsurf="Windsurf",
    Workout="Workout",
    Yoga="Yoga",
}

export class Athlete {
    constructor (
        public id?: string,
        public username?: string,
        public resource_state?: string,
        public firstname?: string,
        public lastname?: string,
        public bio?: string,
        public city?: string,
        public state?: string,
        public country?: string,
        public sex?: string,
        public premium?: string,
        public summit?: string,
        public created_at?: string,
        public updated_at?: string,
        public badge_type_id?: string,
        public weight?: string,
        public profile_medium?: string,
        public profile?: string,
        public friend?: string,
        public follower?: string,
    ) {}
}

export class ClubActivity {
    constructor (
        public athlete?: Athlete,
        public name?: string,
        public distance?: number,
        public moving_time?: number,
        public elapsed_time?: number,
        public total_elevation_gain?: number,
        public sport_type?: ActivitySportType,
        public workout_type?: number,
    ) {}
}